name: Build check
on: 
  pull_request:
    paths-ignore:
      - "*.md"
    types:
      - opened
      - synchronize
      - reopened
  push:
    paths-ignore:
      - "*.md"
    branches:
      - main

jobs:
  build:
    if: false  # This disables the job without removing the code
    uses: ./.github/workflows/build.yml
